---
- name: Install dependencies for Oh-My-Zsh
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    update_cache: "{{ ansible_distribution != 'MacOSX' }}"
    state: latest
    name: "{{ zsh_dependencies }}"

- name: Download and setup Oh-My-Zsh framework for zsh_users
  include_tasks: zsh_for_user.yml
  loop: "{{ zsh_users }}"
  loop_control:
    loop_var: user
  when: user in local_users

- name: Console setup for Debian family distributions
  include_tasks: debian_console_setup.yml
  when: ansible_os_family == 'Debian'
