---
- name: Install dependencies for Oh-My-Zsh
  become: "{{ ansible_distribution != 'MacOSX' }}"
  package:
    update_cache: "{{ ansible_distribution != 'MacOSX' }}"
    state: latest
    name:
      - git
      - zsh

- name: Get local users
  getent:
    database: passwd
    split: ":"

- name: Prepare local users
  set_fact:
    local_users: "{{ getent_passwd | list }}"

- name: Download and setup Oh-My-Zsh framework for zsh_users
  include_tasks: zsh_for_user.yml
  when: user in local_users
  loop: "{{ zsh_users }}"
  loop_control:
    loop_var: user

- name: Console setup for Debian family distributions
  include_tasks: debian_console_setup.yml
  when: ansible_os_family == 'Debian'
