---
- name: Create users
  become: yes
  ansible.builtin.user:
    name: "{{ user.name }}"
    password: "{{ user.password is defined | ternary(user.password, user.name) }}"
    shell: "{{ user.shell is defined | ternary(user.shell, default_shell) }}"
    groups: "{{ user.groups is defined | ternary(user.groups, default_groups) }}"
    append: yes
    state: present
  loop: "{{ create_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
