---
- name: Create users
  become: yes
  user:
    name: "{{ user.name }}"
    password: "{{ user.password | default(user.name) | password_hash('sha512') }}"
    shell: "{{ user.shell | default(default_shell) }}"
    groups: "{{ user.groups | default(default_user_groups) }}"
    append: yes
    state: present
  loop: "{{ create_users }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
  when: create_users is defined
