---
- name: Set root password
  set_fact:
    ansible_become_pass: "{{ root_password }}"
  when: ansible_user == 'root'
  changed_when: no

- name: Sudo control
  include_tasks: sudo.yml
  when: ansible_host != "localhost"
    and ansible_os_family != 'Darwin'

- name: Create users
  include_tasks: create_users.yml
  when: ansible_host != "localhost"

- name: Set auth key
  include_tasks: auth_key.yml
  when: ansible_host != "localhost"

- name: Password authentication control
  include_tasks: password_auth.yml
  when: ansible_host != "localhost"

- name: Root login control
  include_tasks: root_login.yml
  when: ansible_host != "localhost"

- name: Reset ssh connections
  meta: reset_connection
