---
- name: Disable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
    state: present
    backup: yes
  when: not password_auth | bool

- name: Enable password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
    state: present
    backup: yes
  when: password_auth | bool
