---
- name: Disable Password Authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PasswordAuthentication
    line: PasswordAuthentication no
    state: present
    backup: yes

- name: Disable Root Login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
    backup: yes
  notify:
    - Restart sshd
