---
- name: Disable root Login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin no
    state: present
    backup: yes
  when: not root_login | bool
  notify:
    - Restart sshd

- name: Enable root Login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: ^PermitRootLogin
    line: PermitRootLogin yes
    state: present
    backup: yes
  when: root_login | bool
  notify:
    - Restart sshd
