---
- name: Load variables for the target system
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - vars/os
      skip: yes

- import_tasks: install.yml

- name: Initialize shell
  include_tasks: shell.yml
  when: asdf_init_shell | bool

- import_tasks: plugins.yml
