---
asdf_dependencies:
  - git
  - curl

asdf_plugins_dependencies:
  ruby:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev

  nodejs:
    - dirmngr
    - gpg
    - curl
    - gawk
