---
- name: Add initializer
  blockinfile:
    path: ~{{ user }}/.zshrc
    block: |
      . $HOME/.asdf/asdf.sh

      # append completions to fpath
      fpath=(${ASDF_DIR}/completions $fpath)

      # initialise completions with ZSH's compinit
      autoload -Uz compinit && compinit
  when:
    - asdf_init_shell | bool
    - ansible_os_family != 'Darwin'

- name: Add initializer for MacOS
  lineinfile:
    path: ~{{ user }}/.zshrc
    line: . $(brew --prefix asdf)/libexec/asdf.sh
    state: present
  when: ansible_os_family == 'Darwin'
